id: IFDBFF131
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T13:16:13+00:00'
last_modified: '2022-06-07T18:48:21.074193+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W20036
  title: གསོ་རིག་གསུང་རྩོམ་ཕྱོགས་བསྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    69E9:
      image_group_id: I1KG14775
      title: ''
      total_pages: 636
      order: 1
      base_file: 69E9.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
