id: P003277
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 10:52:07.062310
source_metadata:
  id: bdr:W20036
  title: གསོ་རིག་གསུང་རྩོམ་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    2e8dbf17a4604fd5934be66a74c5a9d5:
      image_group_id: I1KG14775
      title: ''
      volume_number: 1
      total_pages: 636
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
